//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_chracterizer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_chracterizer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WellReader.Resource_chracterizer", typeof(Resource_chracterizer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] GeoCom {
            get {
                object obj = ResourceManager.GetObject("GeoCom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GeoCom_3D_Crossplot {
            get {
                object obj = ResourceManager.GetObject("GeoCom_3D_Crossplot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GeoCom_3D_Visualizer {
            get {
                object obj = ResourceManager.GetObject("GeoCom_3D_Visualizer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Geocom_Chat {
            get {
                object obj = ResourceManager.GetObject("Geocom_Chat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap robot12 {
            get {
                object obj = ResourceManager.GetObject("robot12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Well_and_Reservoir_Characterization {
            get {
                object obj = ResourceManager.GetObject("Well_and_Reservoir_Characterization", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Well_Log_Analysis {
            get {
                object obj = ResourceManager.GetObject("Well_Log_Analysis", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
